baseURL = "https://scdhub.org/"
languageCode = "en-us"
title = "Sustainable Community Development Hub"
theme = "amp"

[taxonomies]
  cat = "cat"
  tag = "tag"

LanguageCode= "en-EN"
Title= "Sustainable Community Development Hub"
paginate = 12 
DisqusShortname = "scdhub"
Copyright = "All rights reserved SCD Hub and respective copyright holders - 2019,2018,2017,2016"
canonifyurls = true

[menu]
[[menu.main]]
  name = "SCD Hub"
  url = "/about-scdhub"
  weight = 2

[[menu.main]]
  name = "Mission"
  url = "/about/#mission"
  weight = 21
  parent= "SCD Hub"

[[menu.main]]
  name = "Vision"
  url = "/about/#vision"
  weight = 21
  parent= "SCD Hub"

[[menu.main]]
  name = "Board & Advisors"
  url = "/board"
  weight = 22
  parent= "SCD Hub"

[[menu.main]]
  name = "Partner with SCD Hub"
  url = "/about/#partner"
  weight = 23
  parent= "SCD Hub"

[[menu.main]]
  name = "Non-profit Status"
  url = "/about/#501c3"
  weight = 23
  parent= "SCD Hub"

[[menu.main]]
  name = "Become a member"
  url = "/members"
  weight = 24
  parent= "SCD Hub"

[[menu.main]]
  name = "Get Involved"
  url = "/get-involved"
  weight = 25
  parent= "SCD Hub"

[[menu.main]]
  name = "Donate"
  url = "donate"
  weight = 31
  parent= "SCD Hub"

[[menu.main]]
  name = "Drinking Water"
  url = "/cat/water"
  weight = 33

[[menu.main]]
  name = "Wastewater"
  url = "/cat/wasewater-and-sewerage"
  weight = 33

[[menu.main]]
  name = "Solid Waste"
  url = "/cat/msw"
  weight = 33

[[menu.main]]
  name = "Storage"
  url = "/cat/municipal-solid-waste-storage"
  weight = 13
  parent = "Solid Waste"

[[menu.main]]
  name = "Transfer"
  url = "/cat/msw-transfer"
  weight = 14
  parent = "Solid Waste"

[[menu.main]]
  name = "Disposal"
  url = "/cat/msw-disposal"
  weight = 15
  parent = "Solid Waste"

[[menu.main]]
  name = "Recovery"
  url = "/cat/msw-recovery"
  weight = 15
  parent = "Solid Waste"

[[menu.main]]
  name = "Source"
  url = "/cat/water-sources/"
  weight = 3
  parent = "Drinking Water"

[[menu.main]]
  name = "Procurement"
  url = "/cat/procurement"
  weight = 4
  parent = "Drinking Water"

[[menu.main]]
  name = "Storage"
  url = "/cat/water-storage/"
  weight = 5
  parent = "Drinking Water"

[[menu.main]]
  name = "Treatment"
  url = "/cat/water-treatment/"
  weight = 6
  parent = "Drinking Water"

[[menu.main]]
  name = "Distribution"
  url = "/cat/simple-water-distribution/"
  weight = 7
  parent = "Drinking Water"

[[menu.main]]
  name = "Collection"
  url = "/cat/wastewater-collection/"
  weight = 11
  parent = "Wastewater"

[[menu.main]]
  name = "Transfer"
  url = "/cat/wastewater-transfer"
  weight = 12
  parent = "Wastewater"

[[menu.main]]
  name = "Treatment"
  url = "/cat/treatment"
  weight = 13
  parent = "Wastewater"

[[menu.main]]
  name = "Disposal"
  url = "/cat/disposal"
  weight = 14
  parent = "Wastewater"

[[menu.main]]
  name = "Clinic Topics"
  url = "/videos/2017/07/start-a-clinic/index.html/"
  weight = 35

[[menu.main]]
  name = "Renewables"
  url = "/cat/renewables"
  weight = 15
  parent = "Clinic Topics"

[[menu.main]]
  name = "Shelter"
  url = "/cat/shelter"
  weight = 16
  parent = "Clinic Topics"

[[menu.main]]
  name = "Food"
  url = "/cat/food"
  weight = 17
  parent = "Clinic Topics"

[[menu.main]]
  name = "Propose a clinic"
  url = "/videos/2017/07/start-a-clinic/index.html/#now"
  weight = 25
  parent = "Clinic Topics"

[[menu.main]]
  name = "Topics"
  url = "/clinic/curate"
  weight = 24
  parent = "Clinic Topics"

[[menu.main]]
  name = "- by Tag"
  url = "/tag"
  weight = 28
  parent = "Clinic Topics"

[[menu.main]]
  name = "- by Category"
  url = "/cat"
  weight = 29
  parent = "Clinic Topics"

[params]
    amp = true
    # define which amp-elements you are using globally, these elements will be included in every page
    ampElements = ["amp-accordion","amp-ad","amp-analytics","amp-carousel","amp-iframe","amp-app-banner","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]
  description = "SCD Hub"
  metadescription = "Library of Sustainable Community Development solutions and approaches"
  cover = "images/n0.jpg"
  catcover = "images/n0.jpg"
  author = "Greg Willson"
  authorlocation = "Nederland, Colorado, USA"
  authorwebsite = "http://scdhub.org/greg"
  authorbio= "About SCD Hub"
  logo = "images/logo0.svg"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/scdhub"
  githubName = "sustainablecommunitydevelopmenthub"
  twitterName = "scdhub"
  facebookName = "SCD Hub"
  # codepenName = "biomassives"
  linkedinName = "acmeideal@gmail.com"
  # stackoverflowId = ""
  # keybaseName = ""
  flickrName = "fanjajamii"
  instagramName = "ecocitylearningportal"
  email = "greg@scdhub.org"
  pinterestName = "scd_hub"
  googlePlusName = "acmeideal@gmail.com"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "scdhub"
