baseURL = "https://scdhub.org/"
languageCode = "en-us"
title = "Sustainable Community Development Hub"
theme = "amp"

[markup.goldmark.renderer]
hardWraps = true

[params.search]
enabled = true
keyboardControlled = "topSearchbar"

[params.search.topSearchbar]
enabled = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML","JSON"]

[taxonomies]
  cat = "cat"
  tag = "tag"
  Youtubeid = "youtubeid"
  clinic = "clinic"

LanguageCode= "en-EN"
Title= "Sustainable Community Development Hub"
paginate = 12
DisqusShortname = "scdhub"
Copyright = "Rights respected for copyright holders."
canonifyurls = true

# open source, shelter, drinking water, waste water, solid waste, telecom, energy, climate

[menu]
[[menu.main]]
  name = "SCD Hub"
  url = "/about-scdhub"
  weight = 2

[[menu.main]]
  name = "Mission & Vision"
  url = "/about/#mission"
  weight = 21
  parent= "SCD Hub"

[[menu.main]]
  name = "Board & Advisors"
  url = "/board"
  weight = 22
  parent= "SCD Hub"

[[menu.main]]
  name = "Partner"
  url = "/about/#partner"
  weight = 23
  parent= "SCD Hub"

[[menu.main]]
  name = "Entity"
  url = "/about/#501c3"
  weight = 23
  parent= "SCD Hub"

[[menu.main]]
  name = "Get Involved"
  url = "/get-involved"
  weight = 25
  parent= "SCD Hub"

[[menu.main]]
  name = "Donate"
  url = "/donate"
  weight = 26
  parent= "SCD Hub"

[[menu.main]]
  name = "Solid Waste Storage"
  url = "/cat/municipal-solid-waste-storage/"
  weight = 36
  parent = "Solid Waste"

[[menu.main]]
  name = "Solid Waste Transfer"
  url = "/cat/municipal-solid-waste-transfer/"
  weight = 37
  parent = "Solid Waste"

[[menu.main]]
  name = "Solid Waste Disposal"
  url = "/cat/municipal-solid-waste-disposal/"
  weight = 38
  parent = "Solid Waste"

[[menu.main]]
  name = "Solid Waste Recovery"
  url = "/cat/municipal-solid-waste-recovery/"
  weight = 39
  parent = "Solid Waste"

[[menu.main]]
  name = "Wastewater Collection"
  url = "/cat/wastewater-collection/"
  weight = 40
  parent = "Wastewater"

[[menu.main]]
  name = "Wastewater Transfer"
  url = "/cat/wastewater-transfer"
  weight = 41
  parent = "Wastewater"

[[menu.main]]
  name = "Wastewater Treatment"
  url = "/cat/wastewater-treatment"
  weight = 42
  parent = "Wastewater"

[[menu.main]]
  name = "Wastewater Disposal"
  url = "/cat/disposal"
  weight = 43
  parent = "Wastewater"

[[menu.main]]
  name = "Shelter"
  url = "/cat/shelter"
  weight = 45

[[menu.main]]
  name = "Building Materials"
  url = "/cat/building-materials/"
  weight = 46
  parent = "Shelter"

[[menu.main]]
  name = "Structures"
  url = "/cat/structures"
  weight = 47
  parent = "Shelter"

[[menu.main]]
  name = "Clinics"
  weight = 49

[[menu.main]]
  name = "Water Systems"
  url = "/clinic/peacewaters_clinic"
  weight = 51
  parent = "Clinics"

[[menu.main]]
  name = "Energy"
  url = "/clinic/renewables"
  weight = 52
  parent = "Clinics"

[[menu.main]]
  name = "Telecommunications"
  url = "/clinic/renewables"
  weight = 35
  parent = "Clinics"

[[menu.main]]
  name = "Shelter"
  url = "/cat/shelter"
  weight = 53
  parent = "Clinics"

[[menu.main]]
  name = "Food Security"
  url = "/cat/food"
  weight = 54
  parent = "Clinics"

[[menu.main]]
  name = "Soil Conservation"
  url = "/cat/soil-conservation"
  weight = 54
  parent = "Clinics"

[[menu.main]]
  name = "IT"
  url = "/clinic/information-technology"
  weight = 55
  parent = "Clinics"

[[menu.main]]
  name = "Drinking Water"
  url = "/cat/water"
  weight = 127

[[menu.main]]
  name = "Water Sources"
  url = "/cat/water-sources/"
  weight = 128
  parent = "Drinking Water"

[[menu.main]]
  name = "Water Procurement"
  url = "/cat/procurement"
  weight = 129
  parent = "Drinking Water"

[[menu.main]]
  name = "Water Storage"
  url = "/cat/water-storage/"
  weight = 130
  parent = "Drinking Water"

[[menu.main]]
  name = "Water Treatment"
  url = "/cat/water-treatment/"
  weight = 131
  parent = "Drinking Water"

[[menu.main]]
  name = "Water Distribution"
  url = "/cat/simple-water-distribution/"
  weight = 32
  parent = "Drinking Water"

[params]
    amp = true
    # define which amp-elements you are using globally, these elements will be included in every page
    ampElements = ["amp-accordion","amp-ad","amp-analytics","amp-carousel","amp-iframe","amp-app-banner","amp-dynamic-css-classes","amp-youtube","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]
  description = "SCD Hub"
  metadescription = "Library of Sustainable Community Development solutions and approaches"
  cover = "images/n0.jpg"
  catcover = "images/n0.jpg"
  author = "Greg Willson"
  authorlocation = "Nederland, Colorado, USA"
  authorwebsite = "http://scdhub.org/"
  authorbio= "About SCD Hub"
  logo = "images/logo0.svg"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/scdhub"
  githubName = "sustainablecommunitydevelopmenthub"
  twitterName = "scdhub"
  facebookName = "SCD Hub"
  codepenName = "biomassives"
  linkedinName = "acmeideal@gmail.com"
  # stackoverflowId = ""
  # keybaseName = ""
  flickrName = "fanjajamii"
  instagramName = "ecocitylearningportal"
  email = "greg@scdhub.org"
  pinterestName = "scd_hub"
  googlePlusName = "acmeideal@gmail.com"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "scdhub"
