baseURL = "https://scdhub.netlify.com/"
languageCode = "en-us"
title = "Sustainable Community Development Hub"
theme = "amp"

[taxonomies]
  cat = "cat"
  tag = "tag"

LanguageCode= "en-EN"
Title= "Sustainable Community Development Hub"
paginate = 12 
DisqusShortname = "scdhub"
Copyright = "All rights reserved - 2018"
canonifyurls = true

[menu]
[[menu.main]]
  name = "About Us"
  url = "/"
  weight = 2

[[menu.main]]
  name = "Mission and Vision"
  url = "/mission"
  weight = 21
  parent= "About Us"

[[menu.main]]
  name = "Non-profit Board"
  url = "/board"
  weight = 22
  parent= "About Us"

[[menu.main]]
  name = "Partnership opportunities "
  url = "/partner"
  weight = 23
  parent= "About Us"

[[menu.main]]
  name = "Membership"
  url = "/members"
  weight = 24
  parent= "About Us"

[[menu.main]]
  name = "Get Involved"
  url = "/get-involved"
  weight = 25
  parent= "About Us"

[[menu.main]]
  name = "Drinking Water"
  url = "/tag/drinking-water/"
  weight = 2

[[menu.main]]
  name = "Sources"
  url = "/cat/water-sources/"
  weight = 3
  parent = "Drinking Water"

[[menu.main]]
  name = "Rainwater Catchment"
  url = "/tag/rooftop-water-harvesting/"
  weight = 4
  parent = "Sources"

[[menu.main]]
  name = "Procurement"
  url = "/cat/procurement"
  weight = 4
  parent = "Drinking Water"

[[menu.main]]
  name = "Storage"
  url = "/cat/water-storage/"
  weight = 5
  parent = "Drinking Water"

[[menu.main]]
  name = "Treatment"
  url = "/tag/water-treatment/"
  weight = 6
  parent = "Drinking Water"

[[menu.main]]
  name = "Distribution"
  url = "/cat/simple-water-distribution/"
  weight = 7
  parent = "Drinking Water"

[[menu.main]]
  name = "Wastewater and Sewage"
  url = "/cat/wastewater/"
  weight = 8

[[menu.main]]
  name = "No Collection"
  url = "/cat/no-collection/"
  weight = 01
  parent = "Wastewater and Sewage"

[[menu.main]]
  name = "Collection"
  url = "/cat/water-collection/"
  weight = 11
  parent = "Wastewater and Sewage"

[[menu.main]]
  name = "Transfer"
  url = "/cat/transfer"
  weight = 12
  parent = "Wastewater and Sewage"

[[menu.main]]
  name = "Treatment"
  url = "/cat/treatment"
  weight = 13
  parent = "Wastewater and Sewage"

[[menu.main]]
  name = "Disposal"
  url = "/cat/disposal"
  weight = 14
  parent = "Wastewater and Sewage"

[[menu.main]]
  name = "Curate"
  url = "clinic/curate"
  weight = 24

[[menu.main]]
  name = "for a SCD clinic"
  url = "/videos/2017/07/start-a-clinic/index.html/"
  weight = 25
  parent = "Curate"

[[menu.main]]
  name = "Now"
  url = "/videos/2017/07/start-a-clinic/index.html/#now"
  weight = 25
  parent = "for a SCD clinic"

[[menu.main]]
  name = "by Tag"
  url = "/tag"
  weight = 28
  parent = "Curate"

[[menu.main]]
  name = "by Category"
  url = "/cat"
  weight = 29
  parent = "Curate"

[params]
    amp = true
    # define which amp-elements you are using globally, these elements will be included in every page
    ampElements = ["amp-accordion","amp-ad","amp-analytics","amp-carousel","amp-iframe","amp-app-banner","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]
  description = "SCD Hub"
  metadescription = "Library of Sustainable Community Development solutions and approaches"
  cover = "images/n0.jpg"
  author = "Greg Willson"
  authorlocation = "Nederland, Colorado, USA"
  authorwebsite = "http://scdhub.org/greg"
  authorbio= "About SCD Hub"
  logo = "images/logo0.svg"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/scdhub"
  githubName = "sustainablecommunitydevelopmenthub"
  twitterName = "scdhub"
  facebookName = "SCD Hub"
  # codepenName = "biomassives"
  linkedinName = "acmeideal@gmail.com"
  # stackoverflowId = ""
  # keybaseName = ""
  flickrName = "fanjajamii"
  instagramName = "ecocitylearningportal"
  email = "greg@scdhub.org"
  pinterestName = "scd_hub"
  googlePlusName = "acmeideal@gmail.com"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "scdhub"


