[build]
pubish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "latest"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# A basic redirects rule
[[redirects]]
  from = "/cat/water"
  to = "/water/:splat"
