[build]
pubish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.47"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# A basic redirects rule
[[redirects]]
  from = "/water"
  to = "/cat/water/:splat"
